square: false
type: grid
title: Programmation des appareils
cards:
  - type: custom:mushroom-template-card
    primary: Lave Vaiss
    secondary: ''
    entity: input_boolean.device_request_1
    icon: |-
      {% if is_state('input_boolean.device_request_1', 'on') %}
        mdi:toggle-switch
      {% else %}
        mdi:toggle-switch-off
      {% endif %}
    icon_color: |-
      {% if is_state('input_boolean.device_request_1', 'on') %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: switch.lave_vaisselle
    primary: |-
      {% if is_state('switch.lave_vaisselle', 'on') %}
        Marche
      {% else %}
        Arrêt
      {% endif %}
    secondary: ''
    icon: |-
      {% if is_state('switch.lave_vaisselle', 'on') %}
        mdi:dishwasher
      {% else %}
        mdi:dishwasher-off
      {% endif %}
    icon_color: |-
      {% if is_state('switch.lave_vaisselle', 'on') %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: sensor.lave_vaisselle_power
    primary: '{{ states(''sensor.lave_vaisselle_power'') }} W'
    secondary: ''
    icon: |-
      {% if int(states('sensor.lave_vaisselle_power')) > 0 %}
        mdi:power-on
      {% else %}
        mdi:power-off
      {% endif %}
    icon_color: |-
      {% if int(states('sensor.lave_vaisselle_power')) > 0 %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: more-info
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: input_text.device_duration_1
    primary: '{{ states(''input_text.device_duration_1'') }} Mn'
    secondary: ''
    icon: |-
      {% if is_state('input_text.device_duration_1', '0') %}
        mdi:timer-off-outline
      {% else %}
        mdi:timer-plus-outline
      {% endif %}
    icon_color: |-
      {% if is_state('input_text.device_duration_1', '0') %}
        grey
      {% else %}
        green
      {% endif %}
    layout: vertical
    tap_action:
      action: more-info
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    primary: Seche linge
    secondary: ''
    entity: input_boolean.device_request_2
    icon: |-
      {% if is_state('input_boolean.device_request_2', 'on') %}
        mdi:toggle-switch
      {% else %}
        mdi:toggle-switch-off
      {% endif %}
    icon_color: |-
      {% if is_state('input_boolean.device_request_2', 'on') %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: switch.seche_linge
    primary: |-
      {% if is_state('switch.seche_linge', 'on') %}
        Marche
      {% else %}
        Arrêt
      {% endif %}
    secondary: ''
    icon: |-
      {% if is_state('switch.seche_linge', 'on') %}
        mdi:washing-machine
      {% else %}
        mdi:washing-machine-off
      {% endif %}
    icon_color: |-
      {% if is_state('switch.seche_linge', 'on') %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: sensor.seche_linge_power
    primary: '{{ states(''sensor.seche_linge_power'') }} W'
    secondary: ''
    icon: |-
      {% if int(states('sensor.seche_linge_power')) > 0 %}
        mdi:power-on
      {% else %}
        mdi:power-off
      {% endif %}
    icon_color: |-
      {% if int(states('sensor.seche_linge_power')) > 0 %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: more-info
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: input_text.device_duration_2
    primary: '{{ states(''input_text.device_duration_2'') }} Mn'
    secondary: ''
    icon: |-
      {% if is_state('input_text.device_duration_2', '0') %}
        mdi:timer-off-outline
      {% else %}
        mdi:timer-plus-outline
      {% endif %}
    icon_color: |-
      {% if int(states('input_text.device_duration_2')) > 0 %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: more-info
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    primary: Lave Linge
    secondary: ''
    entity: input_boolean.device_request_3
    icon: |-
      {% if is_state('input_boolean.device_request_3', 'on') %}
        mdi:toggle-switch
      {% else %}
        mdi:toggle-switch-off
      {% endif %}
    icon_color: |-
      {% if is_state('input_boolean.device_request_3', 'on') %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: switch.lave_linge
    primary: |-
      {% if is_state('switch.lave_linge', 'on') %}
        Marche
      {% else %}
        Arrêt
      {% endif %}
    secondary: ''
    icon: |-
      {% if is_state('switch.lave_linge', 'on') %}
        mdi:tumble-dryer
      {% else %}
        mdi:tumble-dryer-off
      {% endif %}
    icon_color: |-
      {% if is_state('switch.lave_linge', 'on') %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: sensor.lave_linge_power
    primary: '{{ states(''sensor.lave_linge_power'') }} W'
    secondary: ''
    icon: |-
      {% if int(states('sensor.lave_linge_power')) > 0 %}
        mdi:power-on
      {% else %}
        mdi:power-off
      {% endif %}
    icon_color: |-
      {% if int(states('sensor.lave_linge_power')) > 0 %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: more-info
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: input_text.device_duration_3
    primary: '{{ states(''input_text.device_duration_3'') }} Mn'
    secondary: ''
    icon: |-
      {% if is_state('input_text.device_duration_3', '0') %}
        mdi:timer-off-outline
      {% else %}
        mdi:timer-plus-outline
      {% endif %}
    icon_color: |-
      {% if int(states('input_text.device_duration_3')) > 0 %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: more-info
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    primary: PAC
    secondary: ''
    entity: input_boolean.device_request_4
    icon: |-
      {% if is_state('input_boolean.device_request_4', 'on') %}
        mdi:toggle-switch
      {% else %}
        mdi:toggle-switch-off
      {% endif %}
    icon_color: |-
      {% if is_state('input_boolean.device_request_4', 'on') %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: switch.relai_pac
    primary: |-
      {% if is_state('switch.relai_pac', 'on') %}
        Marche
      {% else %}
        Arrêt
      {% endif %}
    secondary: ''
    icon: |-
      {% if is_state('switch.relai_pac', 'on') %}
        mdi:hvac
      {% else %}
        mdi:hvac-off
      {% endif %}
    icon_color: |-
      {% if is_state('switch.relai_pac', 'on') %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: sensor.pac_puissance
    primary: '{{ states(''sensor.pac_puissance'') }} W'
    secondary: ''
    icon: |-
      {% if int(states('sensor.pac_puissance')) > 40 %}
        mdi:power-on
      {% else %}
        mdi:power-off
      {% endif %}
    icon_color: |-
      {% if int(states('sensor.pac_puissance')) > 40 %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: more-info
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: input_text.device_duration_4
    primary: '{{ states(''input_text.device_duration_4'') }} Mn'
    secondary: ''
    icon: |-
      {% if is_state('input_text.device_duration_4', '0') %}
        mdi:timer-off-outline
      {% else %}
        mdi:timer-plus-outline
      {% endif %}
    icon_color: |-
      {% if int(states('input_text.device_duration_4')) > 0 %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: more-info
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    primary: Piscine
    secondary: ''
    entity: input_boolean.device_request_5
    icon: |-
      {% if is_state('input_boolean.device_request_5', 'on') %}
        mdi:toggle-switch
      {% else %}
        mdi:toggle-switch-off
      {% endif %}
    icon_color: |-
      {% if is_state('input_boolean.device_request_5', 'on') %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: switch.piscine_pompe_filtration
    primary: |-
      {% if is_state('switch.piscine_pompe_filtration', 'on') %}
        Marche
      {% else %}
        Arrêt
      {% endif %}
    secondary: ''
    icon: |-
      {% if is_state('switch.piscine_pompe_filtration', 'on') %}
        mdi:pump
      {% else %}
        mdi:pump-off
      {% endif %}
    icon_color: |-
      {% if is_state('switch.piscine_pompe_filtration', 'on') %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: sensor.piscine_puissance
    primary: '{{ states(''sensor.piscine_puissance'') }} W'
    secondary: ''
    icon: |-
      {% if int(states('sensor.piscine_puissance')) > 5 %}
        mdi:power-on
      {% else %}
        mdi:power-off
      {% endif %}
    icon_color: |-
      {% if int(states('sensor.piscine_puissance')) > 5 %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: more-info
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: input_text.device_duration_5
    primary: '{{ states(''input_text.device_duration_5'') }} Mn'
    secondary: ''
    icon: |-
      {% if is_state('input_text.device_duration_5', '0') %}
        mdi:timer-off-outline
      {% else %}
        mdi:timer-plus-outline
      {% endif %}
    icon_color: |-
      {% if int(states('input_text.device_duration_5')) > 0 %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: more-info
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    primary: Ch. Voiture
    secondary: ''
    entity: input_boolean.device_request_6
    icon: |-
      {% if is_state('input_boolean.device_request_6', 'on') %}
        mdi:toggle-switch
      {% else %}
        mdi:toggle-switch-off
      {% endif %}
    icon_color: |-
      {% if is_state('input_boolean.device_request_6', 'on') %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: switch.ev_charging
    primary: |-
      {% if is_state('switch.ev_charging', 'on') %}
        Marche
      {% else %}
        Arrêt
      {% endif %}
    secondary: ''
    icon: |-
      {% if is_state('switch.ev_charging', 'on') %}
        mdi:car-electric-outline
      {% else %}
        mdi:car-off
      {% endif %}
    icon_color: |-
      {% if is_state('switch.ev_charging', 'on') %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: sensor.ev_charging_power
    primary: '{{ states(''sensor.ev_charging_power'') }} W'
    secondary: ''
    icon: |-
      {% if int(states('sensor.ev_charging_power')) > 0 %}
        mdi:power-on
      {% else %}
        mdi:power-off
      {% endif %}
    icon_color: |-
      {% if int(states('sensor.ev_charging_power')) > 0 %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: more-info
    hold_action:
      action: more-info
  - type: custom:mushroom-template-card
    entity: input_text.device_duration_6
    primary: '{{ states(''input_text.device_duration_6'') }} Mn'
    secondary: ''
    icon: |-
      {% if is_state('input_text.device_duration_6', '0') %}
        mdi:timer-off-outline
      {% else %}
        mdi:timer-plus-outline
      {% endif %}
    icon_color: |-
      {% if int(states('input_text.device_duration_6')) > 0 %}
        green
      {% else %}
        grey
      {% endif %}
    layout: vertical
    tap_action:
      action: more-info
    hold_action:
      action: more-info
columns: 4
